CREATE DATABASE catalog_app;

CREATE TABLE Book(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_id INT,
  author_id INT,
  label_id INT,
  publish_date DATE,
  archived BOOLEAN,
  publisher VARCHAR,
  cover_state VARCHAR,

  FOREIGN KEY (genre_id) REFERENCES Genre(id)
  FOREIGN KEY (author_id) REFERENCES Author(id)
  FOREIGN KEY (label_id) REFERENCES Label(id)
)

CREATE TABLE Label(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR,
  color VARCHAR
)

CREATE TABLE Albums (
  id SERIAL PRIMARY KEY,
  genre_id INT,
  author_id INT,
  label_id INT,
  publish_date DATE,
  archived BOOLEAN,
  on_spotify BOOLEAN,
  name VARCHAR(100)

  FOREIGN KEY (genre_id) REFERENCES Genre(id)
  FOREIGN KEY (author_id) REFERENCES Author(id)
  FOREIGN KEY (label_id) REFERENCES Label(id)
)

CREATE TABLE Genre (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100)
)

CREATE TABLE Author (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100)
)

CREATE TABLE Games (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR (50),
    genre_id INT,
    author_id INT,
    label_id INT,
    publish_date DATE,
    multiplayer BOOLEAN,
    last_played_at DATE,
    archived BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (genre_id) REFERENCES Genre(id)
    FOREIGN KEY (author_id) REFERENCES Author(id)
    FOREIGN KEY (label_id) REFERENCES Label(id)
);
